### ISSUE TITLE
Inconsistent results with example data

### ISSUE THREAD

**Issue by auesro** [doraadong/UNIFAN#2]
Dear authors,
I have been testing UNIFAN with the example data. The pipeline runs without problems however the end result differs from the one shown in the [notebook](https://github.com/doraadong/UNIFAN/blob/main/tutorails/UNIFAN_example.ipynb): the skeletal muscle satellite cell population is split in two groups as you can see below
![Figure 2022-07-05 093936](https://user-images.githubusercontent.com/24290290/177275736-15820466-8598-4f9b-b924-4294d1242324.png)
![Figure 2022-07-05 093943](https://user-images.githubusercontent.com/24290290/177275758-9fb5d1f8-f847-44fe-b4f2-368fea49cf0b.png)

Is this relevant?

Also, it would be really helpful if you could provide the code necessary to obtain the information represented in the figures 2D and 2E of the Genome Research article.

Thanks!

**Comment by doraadong** [comment]
Hi, thanks for the questions! Regarding your first question, there are some variations between different runs and also, as we noted in the [tutorial](tutorails/UNIFAN_example.ipynb), the number of epochs we used for training in the tutorial is much fewer than the default values. I would recommend you trying with the default number of epochs.

As for your second question, we are working on the tutorials on model interpretation and visualization. Briefly, we make interpretations based on the coefficients learned by the annotator (classifier), which are stored in the state dictionary named classifier_state_dict and with field name "decoder.predictor.0.weight". Each coefficient value for each class (cluster) corresponds to a gene set / gene. The names for the features (gene set / genes) can be found in the saved file input_r_names_path. 

Let us know if you find any other questions.

**Comment by auesro** [comment]
Hi,
Thanks for your reply.
I will repeat the analysis to account for the variation but expected to get "similar" results to the ones in the notebook (running with the same number of epochs).

Regarding my second question, I have found the file `input_r_names_path` but I dont have any variable named `classifier_state_dict` or similar after running the notebook in spyder:
![image](https://user-images.githubusercontent.com/24290290/177379680-4251d198-a9ca-47cf-b92d-19beb3431b30.png)

Any ideas?

**Comment by doraadong** [comment]
Hi, sorry for the confusion! The actual file name is indeed not "classifier_state_dict ". Given we trained the cluster part and the annotator (classifier) together, we saved their state dicts in a single file named: annocluster_model_{number of epochs - 1}.pickle. Within this pickle file, you can find the field name 'state_dict_2' for the state dict of the annotator / classifier. And the coefficients are saved with name "decoder.predictor.0.weight". 

Again, thank you for pointing out this! We will keep you posted about the tutorial on model interpretation.

**Comment by auesro** [comment]
Thank you @doraadong!
I found both datasets. Lets see if I can replicate some of your plots.
Looking forward to the tutorial!

**Comment by doraadong** [comment]
Hi @auesro, the tutorial on cluster annotation is just uploaded. Sorry for the delay! Let me know if you find questions.
